In [1]:
import FundingConsultation

In [2]:
quantitative_data = FundingConsultation.get_quantitative_data()
qualitative_data = FundingConsultation.get_qualitative_data()

In [3]:
# loading the mappings of index numbers to answers for programmatic access
query_indexes = FundingConsultation.get_query_indexes()
# loading the mappings of textual answer fields for programmatic access
textual_indexes = FundingConsultation.get_textual_indexes()

In [4]:
# display the query indexes. These can be queried based on index number
# (e.g., people under 30 would be queried by the number 1 under class 'age')
query_indexes

{'work_life': {'class': 'ordered',
  '1': 'Nee',
  '2': 'Ja, in kleine mate',
  '3': 'Ja, in grote mate'},
 'versie': {'class': 'factor', '1': '1', '2': '2', '3': '3'},
 'age': {'class': 'ordered',
  '1': 'Tot en met 30',
  '2': '31-40',
  '3': '41-50',
  '4': '51-60',
  '5': '61-70',
  '6': '71 plus'},
 'quit': {'class': 'ordered',
  '1': 'Nee',
  '2': 'Ja, in het verleden',
  '3': 'Ja, ik overweeg de wetenschap te verlaten'},
 'major_changes': {'class': 'ordered',
  '1': 'Geen wijzigingen',
  '2': 'Kleine wijzigingen',
  '3': 'Grote wijzigingen'},
 'grant_no': {'class': 'ordered', '0': 'Nee', '1': 'Ja'},
 'grant_pers_nl': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ja, een persoonlijke beurs in Nederland'},
 'grant_pers_foreign': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ja, een persoonlijke beurs in het buitenland, of een Europese beurs'},
 'grant_consortium': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ja, als leider van een team of consortium'},
 'grant_faculty': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ja, een onderzoeksvoorstel voor een faculteit'},
 'grant_university': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ja, een onderzoeksvoorstel voor een universiteit'},
 'grant_foundation': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ja, een onderzoeksvoorstel voor een stichting'},
 'grant_private': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ja, een onderzoeksvoorstel voor een bedrijf of overheid'},
 'nogrant_want': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ik wil dat niet doen.'},
 'nogrant_necessary': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ik heb dat niet nodig. Ik hoef dat niet te doen van mijn leidinggevende.'},
 'nogrant_early': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ik vind het nog te vroeg in mijn carriere om dat te doen.'},
 'nogrant_education': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ik vind onderwijs belangrijker om mijn tijd in te steken.'},
 'nogrant_time': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ik heb er geen tijd voor.'},
 'nogrant_waste': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Ik ben bang dat het zonde van mijn tijd is.'},
 'successful_applications': {'class': 'ordered',
  '1': 'Nee',
  '2': 'Ja, minder dan 10% van mijn aanvragen',
  '3': 'Ja, 10-20% van mijn aanvragen',
  '4': 'Ja, 20-30% van mijn aanvragen',
  '5': 'Ja, meer dan 30% van mijn aanvragen'},
 'body_nwo': {'class': 'ordered', '0': 'Nee', '1': 'NWO'},
 'body_university': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Binnen mijn eigen universiteit/faculteit'},
 'body_foreign': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Een Europese of andere buitenlandse financier'},
 'body_award': {'class': 'ordered', '0': 'Nee', '1': 'Een award-commissie'},
 'body_none': {'class': 'ordered', '0': 'Nee', '1': 'Nee'},
 'rol_supervisor': {'class': 'ordered',
  '1': 'Geen rol',
  '2': 'Een kleine rol',
  '3': 'Een redelijk grote rol',
  '4': 'Een zeer grote rol'},
 'rol_head': {'class': 'ordered',
  '1': 'Geen rol',
  '2': 'Een kleine rol',
  '3': 'Een redelijk grote rol',
  '4': 'Een zeer grote rol'},
 'rol_dean': {'class': 'ordered',
  '1': 'Geen rol',
  '2': 'Een kleine rol',
  '3': 'Een redelijk grote rol',
  '4': 'Een zeer grote rol'},
 'rol_colleagues': {'class': 'ordered',
  '1': 'Geen rol',
  '2': 'Een kleine rol',
  '3': 'Een redelijk grote rol',
  '4': 'Een zeer grote rol'},
 'rol_nwo': {'class': 'ordered',
  '1': 'Geen rol',
  '2': 'Een kleine rol',
  '3': 'Een redelijk grote rol',
  '4': 'Een zeer grote rol'},
 'rol_ocw': {'class': 'ordered',
  '1': 'Geen rol',
  '2': 'Een kleine rol',
  '3': 'Een redelijk grote rol',
  '4': 'Een zeer grote rol'},
 'rol_mentor': {'class': 'ordered',
  '1': 'Geen rol',
  '2': 'Een kleine rol',
  '3': 'Een redelijk grote rol',
  '4': 'Een zeer grote rol'},
 'carreer_success': {'class': 'ordered', '1': 'Nee', '2': 'Ja'},
 'need_no': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Niets, ik ben nu waar ik qua carri√®repad wil zijn'},
 'need_security': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Een beurs voor een aantal jaren om mijn eigen baan veilig te stellen'},
 'need_team': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Een beurs om mijn team uit te breiden'},
 'need_freedom': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Een beurs om wat meer vrijheid te hebben mijn eigen tijd in te delen'},
 'need_equipment': {'class': 'ordered',
  '0': 'Nee',
  '1': 'Een beurs om apparatuur of infrastructuur aan te schaffen.'},
 'award_fair': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'},
 'award_lottery': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'},
 'award_time': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'},
 'award_bandwagon': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'},
 'who_researcher': {'class': 'ordered',
  '1': 'Geen invloed',
  '2': 'Neutraal',
  '3': 'Wat invloed',
  '4': 'Veel invloed'},
 'who_manager': {'class': 'ordered',
  '1': 'Geen invloed',
  '2': 'Neutraal',
  '3': 'Wat invloed',
  '4': 'Veel invloed'},
 'who_university': {'class': 'ordered',
  '1': 'Geen invloed',
  '2': 'Neutraal',
  '3': 'Wat invloed',
  '4': 'Veel invloed'},
 'who_committee': {'class': 'ordered',
  '1': 'Geen invloed',
  '2': 'Neutraal',
  '3': 'Wat invloed',
  '4': 'Veel invloed'},
 'who_government': {'class': 'ordered',
  '1': 'Geen invloed',
  '2': 'Neutraal',
  '3': 'Wat invloed',
  '4': 'Veel invloed'},
 'who_society': {'class': 'ordered',
  '1': 'Geen invloed',
  '2': 'Neutraal',
  '3': 'Wat invloed',
  '4': 'Veel invloed'},
 'co_private': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'},
 'co_connections': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'},
 'co_irrelevant': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'},
 'time_research': {'class': 'ordered',
  '1': 'Geen tijd',
  '2': 'Bijna geen tijd',
  '3': 'Veel tijd',
  '4': 'Bijna al mijn tijd'},
 'time_education': {'class': 'ordered',
  '1': 'Geen tijd',
  '2': 'Bijna geen tijd',
  '3': 'Veel tijd',
  '4': 'Bijna al mijn tijd'},
 'time_phds': {'class': 'ordered',
  '1': 'Geen tijd',
  '2': 'Bijna geen tijd',
  '3': 'Veel tijd',
  '4': 'Bijna al mijn tijd'},
 'time_management_low': {'class': 'ordered',
  '1': 'Geen tijd',
  '2': 'Bijna geen tijd',
  '3': 'Veel tijd',
  '4': 'Bijna al mijn tijd'},
 'time_management_hi': {'class': 'ordered',
  '1': 'Geen tijd',
  '2': 'Bijna geen tijd',
  '3': 'Veel tijd',
  '4': 'Bijna al mijn tijd'},
 'time_service': {'class': 'ordered',
  '1': 'Geen tijd',
  '2': 'Bijna geen tijd',
  '3': 'Veel tijd',
  '4': 'Bijna al mijn tijd'},
 'time_admin': {'class': 'ordered',
  '1': 'Geen tijd',
  '2': 'Bijna geen tijd',
  '3': 'Veel tijd',
  '4': 'Bijna al mijn tijd'},
 'time_involvement': {'class': 'ordered',
  '1': 'Geen tijd',
  '2': 'Bijna geen tijd',
  '3': 'Veel tijd',
  '4': 'Bijna al mijn tijd'},
 'time_patients': {'class': 'ordered',
  '1': 'Geen tijd',
  '2': 'Bijna geen tijd',
  '3': 'Veel tijd',
  '4': 'Bijna al mijn tijd'},
 'review_info': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'},
 'review_confidence': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'},
 'review_informative': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'},
 'review_more': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'},
 'review_government': {'class': 'ordered',
  '1': 'Helemaal niet mee eens',
  '2': 'Niet mee eens',
  '3': 'Neutraal',
  '4': 'Mee eens',
  '5': 'Helemaal mee eens'}}

In [5]:
# display the textual indexes. These should be queried based on the textual answer number
# (e.g., humanities scholars would be queried by the text 'Humanities and social sciences' under class 'displine')
textual_indexes

{'sex': {'class': 'factor', '1': 'Man', '2': 'Vrouw'},
 'successful_applications': {'class': 'ordered',
  '1': 'Nee',
  '2': 'Ja, minder dan 10% van mijn aanvragen',
  '3': 'Ja, 10-20% van mijn aanvragen',
  '4': 'Ja, 20-30% van mijn aanvragen',
  '5': 'Ja, meer dan 30% van mijn aanvragen'},
 'language': {'class': 'factor', '1': 'en', '2': 'nl'},
 'discipline': {'class': 'factor',
  '1': 'Humanities and social sciences',
  '2': 'Beta and medicine',
  '3': 'Economy, business, law'},
 'pos5': {'class': 'factor',
  '1': 'Student-PhD-Postdoc-OA = ECR',
  '2': 'Assistant/associate prof/UD (temporary contract)',
  '3': 'Assistant, associate (permanent)',
  '4': 'Hoogleraar/professor',
  '5': 'Other'},
 'pos9': {'class': 'factor',
  '1': 'Student/Onderzoeksassistent/junior onderzoeker',
  '2': 'PhD',
  '3': 'Postdoc',
  '4': 'Assistant prof/UD (temporary)',
  '5': 'Assistant prof/UD (tenured)',
  '6': 'Associate prof/UHD',
  '7': 'Prof / Hoogleraar',
  '8': 'Anders'},
 'institution': {'class': 'factor',
  '1': 'Academisch Medisch Centrum',
  '2': 'Erasmus MC',
  '3': 'Erasmus Universiteit Rotterdam',
  '4': 'Leids Universitair Medisch Centrum',
  '5': 'Radboud Universiteit Nijmegen',
  '6': 'Rijksuniversiteit Groningen',
  '7': 'Technische Universiteit Delft',
  '8': 'Technische Universiteit Eindhoven',
  '9': 'Universiteit Leiden',
  '10': 'Universiteit Maastricht',
  '11': 'Universiteit Twente',
  '12': 'Universiteit Utrecht',
  '13': 'Universiteit van Amsterdam',
  '14': 'Universiteit van Tilburg',
  '15': 'Vrije Universiteit Amsterdam',
  '16': 'Vrije Universiteit medisch centrum',
  '17': 'Wageningen Universiteit en Research',
  '18': 'Ik werk niet voor een universiteit',
  '19': 'Overig'}}

To select quantitative data on specific conditions, specify a dictionary with each of the conditions (column names) and corresponding values to select on. A dictionary is specified between {accolades}. Each entry in the dictionary contains of a key (the column name, between 'quotes'), a ':' character, and a list between \[square brackets\] of the values you want to select on (which can just be specified as numbers)

In [6]:
# for example, say we want people who for 'major_changes' wanted 'kleine wijzigingen' or 'grote wijzigingen',
# and who are in the youngest age category.
# We can then turns this in a dictionary of conditions as follows:
conditions = {'major_changes': [2, 3], 'age': [1]}

In [7]:
conditions = {'discipline': ['Humanities and social sciences']}

In [8]:
winners = FundingConsultation.select_from_quantitative_data(quantitative_data, conditions)
winners

,ktversie,kt_slider_personal_senior,kt_slider_team,kt_slider_personal_ecr,kt_slider_thematic,kt_slider_thematic_co,kt_slider_small_first,kt_slider_small_second,kt_slider_award,kt_slider_first_ecr,...,kt_team,kt_personal_ecr,kt_thematic,kt_thematic_co,kt_small_first,kt_small_second,kt_award,kt_first_ecr,kt_rolling_ecr,kt_rolling_senior
2,5.0,0.011429,0.120000,0.420000,0.266667,0.054444,0.208571,0.008571,0.06,0.405714,...,0.046667,0.163333,0.266667,0.054444,0.081111,0.003333,0.003333,0.157778,0.090000,0.078889
24,2.0,0.142857,0.142857,0.285714,0.083333,0.083333,0.428571,0.085714,0.00,0.571429,...,0.055556,0.111111,0.083333,0.083333,0.166667,0.033333,0.000000,0.222222,0.111111,0.077778
56,7.0,0.000000,0.420000,0.040000,0.207273,0.000000,0.175000,0.125000,0.00,0.340000,...,0.152727,0.014545,0.207273,0.000000,0.063636,0.045455,0.000000,0.123636,0.392727,0.000000
61,4.0,0.071429,0.068571,0.142857,0.055556,0.000000,0.142857,0.142857,0.50,0.285714,...,0.026667,0.055556,0.055556,0.000000,0.007937,0.055556,0.194444,0.285714,0.447778,0.053580
70,3.0,0.157143,0.314286,0.171429,0.000000,0.000000,0.000000,0.214286,0.00,0.388889,...,0.122222,0.066667,0.000000,0.000000,0.000000,0.083333,0.000000,0.388889,0.194444,0.083333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125,4.0,0.066667,0.166667,0.066667,0.150000,0.150000,0.333333,0.200000,0.10,0.466667,...,0.062500,0.025000,0.150000,0.150000,0.125000,0.075000,0.012500,0.175000,0.150000,0.050000
2131,3.0,0.000000,0.373333,0.706667,0.272500,0.207500,0.160000,0.000000,0.00,0.000000,...,0.140000,0.265000,0.272500,0.207500,0.060000,0.000000,0.000000,0.000000,0.055000,0.000000
2136,8.0,0.066667,0.066667,0.133333,0.062500,0.062500,0.400000,0.133333,0.10,0.533333,...,0.025000,0.050000,0.062500,0.062500,0.150000,0.050000,0.012500,0.200000,0.237500,0.125000
2146,2.0,0.000000,0.000000,0.428571,0.022222,0.000000,0.000000,0.000000,0.00,0.571429,...,0.000000,0.166667,0.022222,0.000000,0.000000,0.000000,0.000000,0.222222,0.533333,0.055556
2151,8.0,0.250000,0.150000,0.400000,0.136364,0.090909,0.125000,0.250000,0.10,0.400000,...,0.054545,0.145455,0.136364,0.090909,0.045455,0.090909,0.009091,0.145455,0.100000,0.090909

The `select_from_quantitative_data()` function has two parameters: the first is the data frame from which a selection should be made, the second a dictionary of conditions to select on.

In [9]:
# we use the above-specified conditions to make a selection from the overall quantitative data
wants_changes_and_is_young = FundingConsultation.select_from_quantitative_data(quantitative_data, conditions)

# display the data frame
wants_changes_and_is_young

,ktversie,kt_slider_personal_senior,kt_slider_team,kt_slider_personal_ecr,kt_slider_thematic,kt_slider_thematic_co,kt_slider_small_first,kt_slider_small_second,kt_slider_award,kt_slider_first_ecr,...,kt_team,kt_personal_ecr,kt_thematic,kt_thematic_co,kt_small_first,kt_small_second,kt_award,kt_first_ecr,kt_rolling_ecr,kt_rolling_senior
2,5.0,0.011429,0.120000,0.420000,0.266667,0.054444,0.208571,0.008571,0.06,0.405714,...,0.046667,0.163333,0.266667,0.054444,0.081111,0.003333,0.003333,0.157778,0.090000,0.078889
24,2.0,0.142857,0.142857,0.285714,0.083333,0.083333,0.428571,0.085714,0.00,0.571429,...,0.055556,0.111111,0.083333,0.083333,0.166667,0.033333,0.000000,0.222222,0.111111,0.077778
56,7.0,0.000000,0.420000,0.040000,0.207273,0.000000,0.175000,0.125000,0.00,0.340000,...,0.152727,0.014545,0.207273,0.000000,0.063636,0.045455,0.000000,0.123636,0.392727,0.000000
61,4.0,0.071429,0.068571,0.142857,0.055556,0.000000,0.142857,0.142857,0.50,0.285714,...,0.026667,0.055556,0.055556,0.000000,0.007937,0.055556,0.194444,0.285714,0.447778,0.053580
70,3.0,0.157143,0.314286,0.171429,0.000000,0.000000,0.000000,0.214286,0.00,0.388889,...,0.122222,0.066667,0.000000,0.000000,0.000000,0.083333,0.000000,0.388889,0.194444,0.083333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125,4.0,0.066667,0.166667,0.066667,0.150000,0.150000,0.333333,0.200000,0.10,0.466667,...,0.062500,0.025000,0.150000,0.150000,0.125000,0.075000,0.012500,0.175000,0.150000,0.050000
2131,3.0,0.000000,0.373333,0.706667,0.272500,0.207500,0.160000,0.000000,0.00,0.000000,...,0.140000,0.265000,0.272500,0.207500,0.060000,0.000000,0.000000,0.000000,0.055000,0.000000
2136,8.0,0.066667,0.066667,0.133333,0.062500,0.062500,0.400000,0.133333,0.10,0.533333,...,0.025000,0.050000,0.062500,0.062500,0.150000,0.050000,0.012500,0.200000,0.237500,0.125000
2146,2.0,0.000000,0.000000,0.428571,0.022222,0.000000,0.000000,0.000000,0.00,0.571429,...,0.000000,0.166667,0.022222,0.000000,0.000000,0.000000,0.000000,0.222222,0.533333,0.055556
2151,8.0,0.250000,0.150000,0.400000,0.136364,0.090909,0.125000,0.250000,0.10,0.400000,...,0.054545,0.145455,0.136364,0.090909,0.045455,0.090909,0.009091,0.145455,0.100000,0.090909

With the `match_to_qualitative_responses()` function, we can look up the qualitative responses for people represented in a particular data frame. The first parameter specifies the data frame for which corresponding answers should be found; the second parameter specifies the data frame with all qualitative answers

In [10]:
# Let's for example do that with the selection we just made (young people wanting change)
wants_changes_and_is_young_qual = FundingConsultation.match_to_qualitative_responses(wants_changes_and_is_young, qualitative_data)

# display the data frame
wants_changes_and_is_young_qual

,id,mkt1,mkt2,mkt3,mkt4,mkt5,mkt6,mkt7,mkt8,mkt9,...,grant_other,nogrant_other,decision_open,idea_science,idea_society,carreer_explain,need_other,opinion,review_positive,review_negative
2,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"dit zijn belachelijke keuzes, er zijn geen alt...",...,NaN,NaN,NaN,NaN,ja genoeg,NaN,een ander systeem,Dat er hier dilemmas en keuzes worden voorgeho...,dat deze plaatsvind,"de keuzes zij te veel voorgekauwd, er bestaan ..."
24,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
56,57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Meer aandacht voor societal impact,NaN,Vliegende start door geld voor aantal PhDs,NaN,Goed om als wetenschappers en docenten terug n...,NaN,NaN
70,71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2125,2140,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2131,2146,"My preference does NOT mean the ""Innovation"" i...","My preference does NOT mean the ""Innovation"" i...","My preference does NOT mean the ""Innovation"" i...",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,"CAP TEACHING LOAD AT 0.25 FTE! Seriously, that...",NaN,"without funding, no results. No results = less...",NaN,NaN,good to force us to allocate and see tradeoffs...,NaN
2136,2151,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2146,2161,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2151,2166,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

This is not so readable, it may be easier to export the non-empty (i.e. non-NaN) answers of any columns you are interested in to a text file. For this, the `export_qualitative_responses()` function can be used.
The first parameter specifies the data frame from which the export should be made, the second the column of interest, and the third a user-specified file name. The file will be exported to the `text/' folder.

In [11]:
# for example, export what the young people wanting change would like to change
# (see the Variablelen_DJA_shortlabels.csv for the column name - in this case, it would be 'which_changes')

FundingConsultation.export_qualitative_responses(wants_changes_and_is_young_qual, 'which_changes', 'changes_demanded_young.txt')